### ISSUE TITLE
extraBuiltins isn't defined

### ISSUE THREAD

**Issue by grahamc** [shlevy/nix-plugins#3]
`extraBuiltins` isn't defined, but `__extraBuiltins` is.

Additionally, it'd be nice to be able to feature-detect on this, so moving it to `builtins.extra` would allow detection based on `(builtins.extra or {}).my-cool-builtin or uhoh`.

**Comment by shlevy** [comment]
Still an issue?

**Comment by grahamc** [comment]
Now it is just a docs issue. :)

**Comment by shlevy** [comment]
Fixed by f413fba28c8968fce6f5e2526fa5de7fb793df38, thanks!
